apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:

      containers:
      - name: chat-app
        image: mokchhedul/project-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
