apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app                   
  namespace: argocd                     
spec:
  project: projectName                

  source:                              
    repoURL: https://github.com/<your-username>/argocd-demos.git   
    targetRevision: main              
    path: manifests/frontend            

  destination:                         
    server: https://kubernetes.default.svc   
    namespace: frontend                     

  syncPolicy:                            
    automated:
      prune: true                        
      selfHeal: true                      
    syncOptions:
      - CreateNamespace=true              
